### ISSUE TITLE
Move ethereum to plugin abstraction

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#100]
Move all ethereum nodes into @magickml/plugins-ethereum

Move values for ethereum key to a component that is injected into the agent manager

![image](https://user-images.githubusercontent.com/18633264/216899371-01a78819-db89-4ca4-8c90-548e5f3fb894.png)

**Comment by alexjorgef** [comment]
working on this in order to migrate #117 implementation to plugin based

**Comment by mrmetaverse** [comment]
almost done

**Comment by alexjorgef** [comment]
> almost done

#239 work almost finished, `solc.compile` function needs to be wrapped with a web worker (https://github.com/ethereum/solc-js/issues/456)

**Comment by mrmetaverse** [comment]
@lalalune @michaelsharpe  is this complete?

**Comment by lalalune** [comment]
Ethereum has been moved to abstraction, service added, just needs some finalization and cleanup
