### ISSUE TITLE
Suggest actions when the vrm file fails to load

### ISSUE THREAD

**Issue by fire** [Oneirocom/Magick#1001]
### Magick version

https://github.com/Oneirocom/Magick/commit/6c461cbeb46aac3218b7fb815461bac623887a60

### System information

Mac Mini, Apple Silicon on Firefox

### Issue description

Suggest actions when the vrm file fails to load

Add a message:

```
**Error: Model Loading Failed**

_Invalid or corrupted VRM file. Check the file and try again._

What to do next:

1. Verify the VRM file's integrity.
2. Ensure the file is in the correct format.
3. Re-download or obtain a new copy of the file if necessary.
4. If the issue persists, contact support with error details.

_Note: The default avatar will continue to be displayed._
```

### Steps to reproduce

Load an invalid vrm like 

[bbb.vrm.zip](https://github.com/Oneirocom/Magick/files/11690289/bbb.vrm.zip)

The model refreshes with no change.

**Comment by ultrabot2022** [comment]
Good suggestion
