### ISSUE TITLE
(feathers) Ensure Discord bot closes and starts back up

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#109]
Currently, Discord bot can hold its connection and receive messages twice. We need to make sure that agents die completely when reset, and that Discord connection is properly handled.

Agent should never respond twice, basically. If the root spell is saved, or the front end is reset, or anything happens that could trigger a reset (hot reload), we want to make sure there are no issues.

![image](https://user-images.githubusercontent.com/18633264/217985200-6cf9bde4-6588-4340-b21d-10eeccb1c8c2.png)

** UPDATE:

I have added some logic to isolate the double-agents. However, if the discord bot crashes, we need to make sure it dies and restarts successfully.

**Comment by alexjorgef** [comment]
at my discord tests, he doesn't answer me twice. because of this: https://github.com/Oneirocom/Magick/blob/main/apps/agent-server/src/connectors/discord.ts#L218-L220 this happening on main branch @lalalune ?
