### ISSUE TITLE
Add multiple trigger outputs to subspells

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#1189]
When a Spell node is created, it only ever has one output trigger, but you can have multiple output nodes in the spell itself. It would be nice if each output node had its associated trigger populated as an output on the Spell node, so that you can branch off into multiple branches of logic based on which output was called. This way you can have logic branching off of a subspell, without janky workarounds like packing the result into the output.

**Comment by michaelsharpe** [comment]
@Knar33 this is actually supported. But we stopped using output trigger nodes. It should work though.
