### ISSUE TITLE
Async responses

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#121]
Right now the whole graph has to complete before returning.

We need to be able to output and trigger responses asynchronously to the graph completing.

For one, this will enable multiple outputs.

Also, this will enable us to run memory tasks etc after responding, which should dramatically improve response time.

This is a prerequisite to multimodal graphs with inputs and outputs from other sources.

**Comment by michaelsharpe** [comment]
In theory websockets would allow that. Not sure it would work under a test model though. Event based system for running agents could work. So a subspell could be it's own agent and waiting to run tasks when it receives a websocket event. That would allow things like async memory storage. Basically could be a 'set and forget' model with pubsub.
