### ISSUE TITLE
Add project filetree drawer

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#142]
The IDE represents the view of a single project space.  Since there can be multiple spells and sub-spells in a project, as well as other "assets" such as finetuned models, individual prompts or blocks of code in the future, we need a modified form of a file tree to make it simple to navigate this and add to it.

For this story, we can use this react file tree: https://github.com/minop1205/react-dnd-treeview

It will require us to add some data properties to the spells and the project so that it matches the structure needed for the library to function.  Some examples use MUI, which we already have installed and so can copy those examples for the styling.

I am attaching a rough design which I did for how this would look.  Individual spells can be unfolded to reveal each of the nodes.  We will need to parse the spell into its individual nodes to display them like this in the tree view.  As we get a few more functional spaces in Magick, like a single prompt engineering environment, it will be possible to associate a prompt "file" to a prompt node, as shown in the design.

<img width="220" alt="Screenshot 2023-02-14 at 10 10 54 AM" src="https://user-images.githubusercontent.com/2397603/218822812-52b286ec-142a-422e-a365-c43aac20bd77.png">

The file tree will be between the nav drawer for screens and the main composer view with all of its tabs.  Here is a screenshot of a similar design pattern from VSCode showing a related design:

<img width="160" alt="Screenshot 2023-02-14 at 10 15 47 AM" src="https://user-images.githubusercontent.com/2397603/218823087-9c3a0c23-d9f4-4eed-a9ae-743bc3a7a05c.png">

<img width="225" alt="Screenshot 2023-02-14 at 10 19 50 AM" src="https://user-images.githubusercontent.com/2397603/218824048-7a03abad-5b23-4ab4-bf17-7516637bfff0.png">

**Comment by mrmetaverse** [comment]
testing integrations

**Comment by mrmetaverse** [comment]
hm... testing again

**Comment by lalalune** [comment]
I got this to the point that it needs design. I think we should close this ticket, move on and make a new ticket for design before we proceed.
