### ISSUE TITLE
Remove !silent and make .display() handle in plugin and log properly on server

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#147]
We are checking if silent and then calling display() if false... this is not a great pattern. We should remove the silent var and display always. On client, display in component as normal. On server, log to console.

**Comment by michaelsharpe** [comment]
The biggest problem with having it always "display" is that the display in the component is really really noisy with objects and long strings.  A better pattern would be to be either seeing a nodes run history in a window, or a way to highlight a nodes output in the console (whose output could be much better formatted too).
