### ISSUE TITLE
Audit ENV variables

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#1491]
We need to remove as many external dependencies from the running Agent class as possible in preparation to bundle the Agent separately.  These envs are found in a few places:
- server core (all the feathers stuff)
- Agent class and dependencies
- Magick Plugins

We have two kinds of environment variables.

1) Application configuration (port, timeouts, etc)
2) External dependencies (portal API, keywords API, database URL, redis, posthog, etc)

We need to remove as many external dependencies as possible to ensure runtime is easy to set up. Some should be made optional, like Posthog, and definitely the external Portal API.

Another task will be made to make dependencies optional.

**Comment by HaruHunab1320** [comment]
✅ Feathers

**Comment by HaruHunab1320** [comment]
✅ Plugins

Dependencies

- CREDENTIALS_ENCRYPTION_KEY defaults to ‘key’

Configuration

- PINO_LOG_LEVEL

**Comment by HaruHunab1320** [comment]
### Required Keys for Agents.ts

Configuration

- NODE_ENV defaults to development

### Optional Keys

Configuration

- AGENT_HEARTBEAT_INTERVAL_MSEC defaults to 10 seconds
- PINO_LOG_LEVEL defaults to info
