### ISSUE TITLE
Add dreambooth models and reference in image generation

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#180]
Add the ability to create custom dreambooth models to the "fine tuning" tab
https://github.com/smy20011/dreambooth-gui

Update image generation to use bananaml, allow it to reference this model, set up bananaml model to load dreambooth model:
https://github.com/bananaml/serverless-template-dreambooth-inference

**Comment by michaelsharpe** [comment]
These sorts of tasks need to have a design pass over them for how we fit them in properly with the IDE design system. We want ti try to reduce design debt as we grow so we don't have to go back over a bunch of random screens that all look kinds different.
