### ISSUE TITLE
Style Agent Window

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#185]
Right now each Discord agent is a big waste of space.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/18633264/219944030-a68164b6-b3ce-4cfc-a546-4f6d231df0b9.png">

**Comment by michaelsharpe** [comment]
@FabriceIRANKUNDA I will be working out some designs for this, so please hold off on it until I have attached some designs.

**Comment by lalalune** [comment]
![image](https://user-images.githubusercontent.com/18633264/220458086-fc740792-48ce-4967-b55b-d69102162e31.png)

**Comment by michaelsharpe** [comment]
@lalalune I will be adding to this design to flesh out the right hand side, but basic idea is that variables and connector data will all go in here.

**Comment by lalalune** [comment]
Solved in https://github.com/Oneirocom/Magick/pull/231
