### ISSUE TITLE
Document how these buttons work and what add a descriptive note

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#189]
In the discord agent we have these values..
<img width="608" alt="Screenshot 2023-02-19 at 8 38 37 AM" src="https://user-images.githubusercontent.com/18633264/219961768-f54d452c-7729-4e55-be1f-797234508545.png">

- Find a better descriptive name for each
- Write a one line description for each
- Add the text below the grid (or whatever looks good-enough for now)

The goal is to make the discord agent UI more explainable to the user

**Comment by michaelsharpe** [comment]
@lalalune I will do a pass over the whole agent flow with an eye to UX, and chat with @dragonlvx about this as well.  Lets have some specs in place before this goes into dev.

**Comment by lalalune** [comment]
I think we're just not clear on the difference between starting words, bot name and bot name regex, so we need clearer descriptions or labels.

**Comment by lalalune** [comment]
Fixed in https://github.com/Oneirocom/Magick/pull/231

<img width="654" alt="Screenshot 2023-02-25 at 5 39 50 PM" src="https://user-images.githubusercontent.com/18633264/221387676-5193ebed-0bfc-42ce-8139-5bcea0ecc929.png">
