### ISSUE TITLE
Robust agent runner

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#199]
Agent runner should be designed in a way that it works like a queue, and could be distributed across multiple servers.

- agent loop runs and sets the "updated_at" value to current time
- if agent's dirty flag is false, the agent will restart with new variable settings
- agent runner checks for any agents that have an "updated_at" value greater than 15 seconds
- if an agent is "enabled" but hasn't been updated, the runner claims it, starts the agent and starts updating updated_at

the goal is that two or more runners could be looking at the database and reasonably distribute the load of agents between them without starting the same agent twice

When process.env.SINGLE_USER_MODE=false, agent checks for all projectIds -- if SINGLE_USER_MODE is true, agent checks only for its specific projectId. This allows us to have a public database where users don't accidentally launch each other's agents.

**Comment by michaelsharpe** [comment]
We will also need to enable some kind of autoscaling. Not sure if we scale up the agent to handle more requests by making more instances of the same Agents, or if the spell runner can load up multiple instances of the same spell if all of them are working. The queue system would work well for this for predicting load. 

I also like the idea that a full project could go into its own k8 pod, and scale that way.

**Comment by lalalune** [comment]
I think we will approach this once we have everything deployed. I'm going to close this now as the agent is relatively robust. Scaling the agent and multi-tenancy will happen next in a separate sprint.
