### ISSUE TITLE
Auto-generate inputs and outputs in function header for code nodes

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#201]
Right now we have untyped function headers like `function worker(inputs, outputs, context) {`

would be nice to have more like
```
function worker(
// inputs
{
  mySocketInput1
},
//outputs
{
  mySocketOutput1
},
context
)
```

with these values auto-inserted from the inspector.

**Comment by michaelsharpe** [comment]
Ooooh lovely idea!

Generator node could do something similar. We could parse handlebars template for variables and automatically add sockets to the component.
