### ISSUE TITLE
[BUG] Subspell dropdown

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#215]
if you try typing a new spell into the dropdown of the spell component in the inspector, the text is blocked out by something.  

Expected behaviour: I can type on the dropdown, see what I type, and then create and open the new spell.

Related to 151, and on the 151 spell branch

**Comment by lalalune** [comment]
If I click away from the spell and back it appears messed up

<img width="685" alt="Screenshot 2023-03-03 at 4 22 08 AM" src="https://user-images.githubusercontent.com/18633264/222719062-e592825c-fa4f-402e-8c1f-5049a12ee671.png">
