### ISSUE TITLE
Langchain Integration

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#221]
Langchain is awesome, and we could use it for a lot of stuff.

- Replace OpenAI calls with Langchain's OpenAI import
- Add Cohere as an option everywhere

Document loaders
- Add all document loaders as nodes
- Add embedding support
- Add Text Splitters
- Add Vectorstores

Tools
- Expose tools for use

Once we have these in, we can look at adding the pre-made chains

We also want to make sure that langchain is available as an import to the js and python code node

**Comment by michaelsharpe** [comment]
Let's do it. Should be easy to transform most classes into nodes.
