### ISSUE TITLE
Discord Voice not working on m1

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#230]
dyld[60648]: missing symbol called

**Comment by sshivaditya2019** [comment]
@lalalune Possible Solution https://gist.github.com/adrienjoly/e29a6e73fb7e701eefd80ff9bde9abeb

**Comment by michaelsharpe** [comment]
@VanLazyDuck Is there any status report on this?  if you are blocked, please let us know.  This has been in flight for a while.

**Comment by VanLazyDuck** [comment]
I cannot re-create this bug on the m1 devices I have. No errors relating lib or dependencies thrown.

![Image](https://user-images.githubusercontent.com/127198220/228795513-92bcc245-83e3-4896-8b23-cb38f1f373cb.png)
![Image](https://user-images.githubusercontent.com/127198220/228795512-b539ebbb-cb80-41d4-90a2-86d06ea0a017.png)

**Comment by fire** [comment]
Closing due to a tester unable to recreate. Reopen if still in error.
