### ISSUE TITLE
Add sqlite support and branch all calls to properly handle sqlite or Postgres

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#234]
Right now we are using Postgres. In order to let people get up and running quickly, we have a cloud hosted test database. However, this has some unintended security issues.

For local users, we want to add the default option to start with sqlite. We want to init the server with either Postgres or sqlite depending on the .env

Tasks

Add DATABASE_TYPE to .env
set DATABASE_URL to sqlite file path
if DATABASE_TYPE===’sqlite’, knee should always save there instead of postgres
Make sure all Postgres calls, custom knee queries, etc are handled using sqlite if the env is set
Prepare PR where sqlite is default and Postgres settings are comments out
Add to database

**Comment by michaelsharpe** [comment]
Much easier now than we don't have the prisma issues. Good call.

**Comment by mrmetaverse** [comment]
in progress bounty
