### ISSUE TITLE
Validate Plugins In Agent Window - If user selects a spell and enables an input, warn/disable if input not in spell

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#237]
Blocked by https://github.com/Oneirocom/Magick/pull/242

Bots might fail if someone uses the regular input instead of the discord input. if theres only one input (80% of the time) then we should allow this)

**Comment by michaelsharpe** [comment]
It would be good to set up a validation pattern and helper library for spell validation. That will go a long way I think to help users. 

We can also only show the option to enable discord if a discord node has been added to the spell.

**Comment by mrmetaverse** [comment]
Do not give someone the ability to activate discord if it hasn't been ---- gray it out.
