### ISSUE TITLE
Plugin system for connectors

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#24]
Connectors currently are all different and loaded all together in the entity. We need a proposal and implementation of a module system for the connectors. A clean API that can be generalized to all our connectors. We should start with migrating over a single connector as a trial. Let's start with discord.

**Comment by lalalune** [comment]
Plugins should have
 - dependency manifest
 - containers
 - configuration and defaults
 - agent init and deinit function
 - agent configuration options
 - magick interface functions and types
 - windows
 - nodes

**Comment by alexjorgef** [comment]
@lalalune Discord will be included in future relasesas integrated with agent?
