### ISSUE TITLE
Add node id, params, and spell name to requests

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#257]
We should track requests with the node id and spell name. That will allow us to see the performance of any node on the graph, and visualize a spells run history based on nodes. We can also fine tune models on the data from specific nodes. 

It is important that we see nodes on spells as data collectors to fine tune their own smaller model replacements.

**Comment by michaelsharpe** [comment]
In theory it would actually be awesome for every node of the graph to store its run data.  We could use this for inspecting the run history of any node, rerunning failed node runs, etc.
This would include any completion nodes, but would also actually mean that any node we add with any AI functionality or whatever will get logged.

Rete plugins let us modify behaviour per node run.  So we could have a plugin which grabs the data we want from the node (nodes data property, the input values, its ID, the spell that is running, date time stamp, etc), maybe check latency by grabbing time, running the nodes worker, checking the time again, and then storing the outputs of the worker.

**Comment by lalalune** [comment]
Everything has been added to this here: https://github.com/Oneirocom/Magick/pull/276

However, the spell has not been supplied. We should send either the spell name and spell Id or the whole spell data (which can be viewed in the full data view).

**Comment by lalalune** [comment]
The params are already there. I added the node ID and tried to add the spell, but it didn't work out of the box. It may not be properly referenced or not exist at all on the node.data (but I think it should!)

@michaelsharpe if you have any idea where to inject the spell into the node data or get it, that's the missing piece. If we say node.data.spell = spell, we're done with this task.

**Comment by michaelsharpe** [comment]
Actually. There should be a function in the magick interface in the worker called 'getCurrentSpell' as I needed it somewhere else too.
