### ISSUE TITLE
Fix autosave

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#26]
Autosave is currently disabled.  There is a tendency, though hard to reproduce, when the autosave will case a whole spell to be wiped.  It is likely on a spell reload event when the spell is empty for a brief moment, and that is registered as a diff.

**Comment by lalalune** [comment]
Autosave is not disabled, but it's failing to build the diff in the OtJson lib call

**Comment by lalalune** [comment]
Working for me

**Comment by michaelsharpe** [comment]
Really? Did we add in a diff save endpoint? Or is it still auto saving the whole graph (that's a ton of unnecessary data of the wire regularly if it is)
