### ISSUE TITLE
Generator gets event injection

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#261]
<img width="161" alt="Screenshot 2023-03-01 at 1 39 06 AM" src="https://user-images.githubusercontent.com/18633264/222101257-4f1a1229-fad1-4209-a1ad-44978d1a45c9.png">

**Comment by Adrian-Serna** [comment]
Are you referring here to this problem that does not allow me to connect the input to an echo in my initial test? or is it not the same thing? 

<img width="633" alt="Capture d’écran 2023-03-02 à 09 59 14" src="https://user-images.githubusercontent.com/30478112/222381096-e723b67d-b872-4018-a5f1-5cb014d01670.png">

Just to know if this is considered a problem or am I missing something. Thank you.

**Comment by lalalune** [comment]
Hello @Adrian-Serna -- yes, you will need to use an "event destructure" node to get the "content" from your event.

Sorry this is confusing, going to try to make it simpler.

**Comment by lalalune** [comment]
Fixed in rest-api and probably development
