### ISSUE TITLE
Generated socket inputs should go below hardcoded socket inputs

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#262]
We should make the generated sockets go below. This way we can have the triggers as the top for all of our nodes.

<img width="253" alt="Screenshot 2023-03-01 at 1 53 03 AM" src="https://user-images.githubusercontent.com/18633264/222104845-74e9bd1d-6877-43c8-8835-ca04c4400178.png">

**Comment by BMO-tech** [comment]
Is `trigger` the only hardcoded socket type?

**Comment by lalalune** [comment]
Various nodes have various coded / non-generated inputs. Generally the problem we're having is that the generated inputs sit on top. However if you refresh it seems to change.
