### ISSUE TITLE
Error: No triggered node found

### ISSUE THREAD

**Issue by Adrian-Serna** [Oneirocom/Magick#269]
Hi, I'm trying to make my first module in Magick, but no matter what I do, even with the simplest configuration, I always get the same problem: 
"triggeredNode undefined
error: Error: No triggered node found" in the terminal
"Uncaught (in promise) Error: No triggered node found" in the console.

First of all, my general configuration runs apparently fine, with only one problem in the browser console: Uncaught (in promise) Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (index.ts:269:28)
    at Logger.throwError (index.ts:281:20)
    at AlchemyWebSocketProvider.<anonymous> (json-rpc-provider.ts:483:23)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.ts:16:1)

I don't know if there is any relation, here is one of the various configurations I have tried to throw.

Thanks for any light you can shed.

<img width="1551" alt="Capture d’écran 2023-03-02 à 11 23 57" src="https://user-images.githubusercontent.com/30478112/222404500-9de5edef-9902-4bc2-9ea6-855a15342955.png">

**Comment by lalalune** [comment]
Solved in the latest development

**Comment by Adrian-Serna** [comment]
confirmed, thank you!
