### ISSUE TITLE
[BUG] Designs for socket creation dropdown are off

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#270]
Currently the socket name has "data" on it in the component, and the socket name is below the socket in the list as a label of some kind.  Socket name should go inside the component.

Also, we should hide the socket type selector until we have the ability to change the socket type.

![Image](https://user-images.githubusercontent.com/2397603/222573282-72957cbd-7ea3-4078-bb6a-2a31972313aa.png)

**Comment by mrmetaverse** [comment]
comment out for now

**Comment by lalalune** [comment]
Fixed this in my local, will push
