### ISSUE TITLE
Getting an error on `npm i`

### ISSUE THREAD

**Issue by dglazkov** [Oneirocom/Magick#273]
Hi, I was hoping to play with Magick a bit, and ran into this issue, pretty much right away:

```
$ npm i                     

> magick@0.1.0 postinstall
> node config/config-plugins.js && node config/config-project.js && npm run migrate

Installation plugins undefined

> magick@0.1.0 migrate
> nx run @magickml/server:migrate


> nx run @magickml/server:migrate

> @magickml/server@0.1.0 migrate
> knex migrate:latest
Requiring external module ts-node/register
Knex: run
$ npm install sqlite3 --save
Cannot find module '/Users/dimitri/Documents/code/Magick/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
Require stack:
- /Users/dimitri/Documents/code/Magick/node_modules/sqlite3/lib/sqlite3-binding.js
- /Users/dimitri/Documents/code/Magick/node_modules/sqlite3/lib/sqlite3.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/lib/dialects/sqlite3/index.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/lib/dialects/index.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/lib/knex-builder/Knex.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/lib/index.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/knex.js
- /Users/dimitri/Documents/code/Magick/node_modules/knex/bin/cli.js
```

I wonder if that's related to the recent switch to sqlite?

**Comment by lalalune** [comment]
Hi @dglazkov 

It looks like you are on an M1 -- I am as well. I find that I have an error with the vss plugin for vector search (which the author is aware of) but the sqlite is working for me without having to install anything additional, other than running once.

The "Installation plugins undefined" is fortunately just a vestigal log.

If you want to get around this and don't wish to debug, you can change add DB_TYPE=postgres in the .env.local and set the DATABASE_URL=<your connection string>

I suggest supabase, and installing the pgvector so you can do similarity search
https://supabase.com/docs/guides/database/extensions/pgvector

**Comment by lalalune** [comment]
Closing this. If you have any issues, join us on Discord, happy to help.

https://discord.gg/magickml
