### ISSUE TITLE
View last run data on any node

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#281]
Right now it is a bit hard to debug Magick. When we are working on a pipeline, we want to see what data came in and what data came out from any node.

We can add this data to the inspector, or make it filtered in the console, or otherwise surfaced. When I click on a node, I want to see it's inputs and outputs somewhere.

Also, when I highlight over an input or output, I'd like to be able to right click and "view last run data". This could appear in the inspect or in a modal or wherever makes sense.

**Comment by michaelsharpe** [comment]
I think I have a similar issue around. I was thinking we could have a history window that will show the run history of any node you click on. Each run would be a table row with an accordion. You can open it up to see specific data about the run. Would need to work out what data. 

I like the idea too of a workspace tab which you could open which just focuses on a single node with a bunch of windows relevant to that nodes functioning.
