### ISSUE TITLE
Drag to select nodes

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#282]
It would be awesome if we could select many nodes with a mouse drag and then move them around.  This is the precursor to being able to select a group of nodes and create a subspell from them.

This would warrant a few changes:
- click and drag mouse around doesn't pan the canvas.  It will select nodes
- pan around would probably be holding down control and moving the cursor around

This would be much more in keeping with most other canvas based interactions.

**Comment by lalalune** [comment]
Shift + drag works. We should make this the default behavior and move panning to a shift or command+drag... whatever Unreal Engine uses should be our defaults, basically.
