### ISSUE TITLE
Create subspell from selected nodes

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#284]
Once we can select a group of nodes, we want the ability to turn all selected components into their own subspell.  This would make a new spell with all the right inputs and outputs required to wire it up to the parent components.

**Comment by gadillacer** [comment]
> Once we can select a group of nodes, we want the ability to turn all selected components into their own subspell. This would make a new spell with all the right inputs and outputs required to wire it up to the parent components.

Hello, I'm working on this issue.

Can I ask you what a subspell is?
I couldn't find much information. Idk how to create them in the IDE.

This is what I've found

`packages/editor/src/editor.ts`
```
  editor.onSpellUpdated = (spellName: string, callback: () => void) => {
    return magick.onSubspellUpdated(spellName, callback)
  }
```
