### ISSUE TITLE
Move agent name edit to details page

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#292]
Right now the edit is in the list. We should move the edit button to the details page.

Also, it should be styled to not change from current edit style. The input should be styled to be same as header, other than the cursor to type and the edit button becoming the accept/cancel

<img width="389" alt="Screenshot 2023-03-03 at 3 24 00 AM" src="https://user-images.githubusercontent.com/18633264/222708232-825be19a-4e65-4d08-a101-4c206bb02255.png">

**Comment by sshivaditya2019** [comment]
Fixed in #303
