### ISSUE TITLE
Throw toast if spell with same name already exists

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#293]
If I make a spell "testing", then I make another one, nothing happens. I should get a toast from the snackbar that says that a spell with that name already exists.

<img width="601" alt="Screenshot 2023-03-03 at 3 56 13 AM" src="https://user-images.githubusercontent.com/18633264/222714439-c40d55f2-b206-426c-b67e-3fef87141dec.png">

**Comment by sshivaditya2019** [comment]
Fixed in #303
