### ISSUE TITLE
"apiKey" is undefined on makeCompletion.ta

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#300]
Error: Even though OpenAI Api key is set in the UI, it's undefined when running a Text Completion node. This causes a 401 Unauthorized error.

Expected behavior: The node gets the correct apiKey and creates the completion.

How to reproduce:
When running a Text Completion node I saw the following error, since I also didn't complete the `.env` file with such key:

<img width="1878" alt="Screenshot 2023-03-03 at 17 55 02" src="https://user-images.githubusercontent.com/20055787/222780124-273a888b-08ce-46f0-9e8f-9d7b67442e67.png">

**Comment by lalalune** [comment]
Solved
