### ISSUE TITLE
delete .env or add it to .gitignore

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#301]
The main repo has a .env file. 
It should either be removed (in favor of .env.local) or added to .gitignore.

**Comment by lalalune** [comment]
.env is meant to be there as part of the dotenv flow spec

an ignored .env.local is auto-generated when you install

**Comment by 0xPetra** [comment]
Yes, but people might complete it at commit without realizing they should use .env.local.
I know OpenAI tracks Tokens on Github and disables them when they find them. Not sure the other services. Wouldn't risk it.
