### ISSUE TITLE
Create Error message: Can’t connect "Type" with "Type"

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#304]
PROBLEM: I couldn't connect the output from “Input - Default” to “Text” on “Text Completion”
As @lalalune explained we need an "Event Deconstructor" in the middle. 

SOLUTION: Alert users why they can't connect something. i.e: "You need a "string" and this outputs a "Event".
ADDITIONAL: A link to the docs related to what each thing outputs/inputs.

<img width="1657" alt="Screenshot 2023-03-03 at 14 30 58" src="https://user-images.githubusercontent.com/20055787/222906688-8bc73ff0-7558-4044-bac2-d848259f67ed.png">

**Comment by lalalune** [comment]
Need an "Event Destructure" node

<img width="369" alt="Screenshot 2023-03-05 at 3 18 43 PM" src="https://user-images.githubusercontent.com/18633264/222991687-aea2e5d3-a9e0-47b0-93ab-2f9c6161b860.png">
