### ISSUE TITLE
Unreliant behaviour with Input Default. [BUG]

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#305]
Even though I set “Use default” in an "Input" node, it was using the other one (which didn't have the default setting). 

Tried switching a couple of things, until got it working. But I think it's not working properly. 

<img width="308" alt="Screenshot 2023-03-03 at 15 10 32" src="https://user-images.githubusercontent.com/20055787/222906994-37097658-ee53-4e0f-bdb0-e943992f1f72.png">

**Comment by lalalune** [comment]
Should be fixed except blocked by the input sockets issue
