### ISSUE TITLE
Text on Discord api

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#307]
There are Application Public Token and Bot Token. 
The wording should match Discord’s so it’s the same and not confusing for new users.

Also a link to a tutorial on how to link for this and add the bot to the server would be super useful. I liked this doc:
https://discordpy.readthedocs.io/en/stable/discord.html

<img width="290" alt="Screenshot 2023-03-03 at 18 30 18" src="https://user-images.githubusercontent.com/20055787/222907050-52ed8666-fc10-44e0-9cbb-10570705f47d.png">

**Comment by lalalune** [comment]
Lets make it the same as Discord.js and link to here: https://discordjs.guide/preparations/setting-up-a-bot-application.html#creating-your-bot

We should also make a copy-and-pasteable bot link:
https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links

**Comment by lalalune** [comment]
Fixed
