### ISSUE TITLE
NX plugin generator

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#308]
We should make a custom Nx generator that creates either a client, server, or shared plugin. 

Instructions are here. Just need to make the generators and copy over an existing plugin and strip it down to a hello world example. 

https://nx.dev/recipes/generators/local-generators

**Comment by fire** [comment]
I did some design for this. Free free to edit this comment.

## What is the Context and Problem Statement this is trying to solve?

Make it easier to get started with Magick IDE plugins and to publish new Magick IDE plugins.

## Describe the proposed option and how it helps to overcome the problem or limitation

A custom Nx generator makes it easier for Magick developers to get started.

## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams.

Create a custom Nx generator that creates:

1. Client
2. Server
3. Shared plugin

## Is there a reason why this should be core and done by us?

We develop Magick and developer onboarding is important.

## Negative Consequences

More plugins need more QA to ensure quality.

## Positive Consequences

More features to make the users lives better.
