### ISSUE TITLE
Add cmd s, cmd z, etc

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#316]
Right now we are using the option key for all commands.

That's fine, but it's not intuitive. We should do a greedy approach, and make both option work everything, *and* command work where it makes sense. some things like command+w will now work and will close the window. we should try to capture those and warn users.

- [x] add command on mac, ctrl on windows and linux for save, copy/paste, new, etc
- [ ] add handlers for things like ctrl w to throw a warning (if possible) to prevent user from closing on accident
- [ ] save on close if possible

**Comment by lalalune** [comment]
Basically lets just make sure these all work reliably in a way that isn't confusing, ideally following Unreal Engine paradigm

**Comment by coffeeorgreentea** [comment]
After further looking i don't think step 2 is possible
https://github.com/JohannesKlauss/react-hotkeys-hook/issues/550#issuecomment-859536246

**Comment by fire** [comment]
@coffeeorgreentea Is this done?

**Comment by coffeeorgreentea** [comment]
> @coffeeorgreentea Is this done?

yes this was part of another ticket
