### ISSUE TITLE
Export editor components as React Library

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#328]
The goal is to export all of the editor components as a React library which is compatible with Next.js and standard react + vite.

The "gotcha" here is that we need to export all of the components, provider and state and recompose this inside next.js pages.

- [ ] Separate out all components and export for package
- [ ] Editor, client etc still work in Magick
- [ ] Next.js example app that imports the components and demonstrates the editor running

Some config and injection may be needed for this to work.

**Comment by fire** [comment]
Is this related to the removal of iframe enhancement?

You also mentined https://github.com/Oneirocom/Magick/issues/407 was fixed.
