### ISSUE TITLE
Fill the empty screen with info like new features added and other updates

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#357]
once we have the file tree ( #142 ) we should use the empty screen space when there is no tab for user information and onboarding.  VSCode has this pattern and it works really well.  Would be awesome if we could hook it up to something we can easily update from an externals source.  Could mention new features we have added, etc.

![Image](https://user-images.githubusercontent.com/2397603/224468869-fbbc923f-18a4-4575-814c-3604f90e904a.png)

**Comment by fire** [comment]
1. Do we want this?
2. Is there a design?
3. How important is this?

**Comment by dragonlvx** [comment]
@michaelsharpe if you wanna get together at some point to discuss what you're thinking, we can collaborate on some designs. Then we can add a priority and include it in a sprint.
