### ISSUE TITLE
Socket inputs can be "optional", italic / transparent

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#369]
Right now we have no way to indicate which sockets *must* be filled vs which are optional.

Filled is the default, but some should be marked as optional. The text for those sockets should be transparent and the socket input itself should be slightly differen, slightly transparent perhaps.

**Comment by FabriceIRANKUNDA** [comment]
> Right now we have no way to indicate which sockets _must_ be filled vs which are optional.
> 
> Filled is the default, but some should be marked as optional. The text for those sockets should be transparent and the socket input itself should be slightly differen, slightly transparent perhaps.

How are we going to know those that are optional?

**Comment by dragonlvx** [comment]
![Image](https://github.com/Oneirocom/Magick/assets/125402897/c66d01c2-fbca-4654-b3f3-0d5a48659e79)

I'm not sure how we know which sockets are optional and which are a MUST, but here are some quick designs that could help with what it should look like.
I'm open to feedback as always :)

**Comment by fire** [comment]
Will this conflict with or make upgrades to rete.js 2.0 harder?

**Comment by dragonlvx** [comment]
I was just informed that the trigger sockets should not be a MUST, but the red outline would be good for the sockets that DO need to be connected.

Required sockets would be defined by a coder when they set up a socket on the node.

Also @fire we cant wait to improve the editor until we get the upgrade done, as it could be 2-4 months until it is finished, whenever we can get the devs time to do it.
