### ISSUE TITLE
Add node custom name for all nodes, add to React Magick Rete Node

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#370]
Right now some nodes have a custom name field and some do not. However, all of it is a bit confusing.

- [ ] Every node has the option to have a custom name, empty / off by default
- [ ] Name is displayed next to the Node Type on the node
- [ ] Remove custom "name" field and logic from the nodes that have it so they all work the same

For now the React Node can render the custom name next to the node name, eg "Event Store | Conversation"

**Comment by michaelsharpe** [comment]
I think we have a similar issue. We can make a name plugin which adds a name inspector control to every component. Nice and clean.

**Comment by michaelsharpe** [comment]
Happy to either execute this or help give some guidance to @FabriceIRANKUNDA. I already have a pretty clear idea in my head how this would go.

**Comment by FabriceIRANKUNDA** [comment]
> Happy to either execute this or help give some guidance to @FabriceIRANKUNDA. I already have a pretty clear idea in my head how this would go.

Please let's chat and give some guidance about this!
