### ISSUE TITLE
Light Theme + Move All Styles to Theme + Add Theme Switch

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#376]
A light theme has been requested.

- [ ] Add light theme
- [ ] Move all hardcoded styles into theme and use vars so light theme works well
- [ ] Add theme switch to the "settings" page

**Comment by michaelsharpe** [comment]
We will need to work on designs for this first before any dev takes a crack at it please. 

We will also be styling the dark theme to better match the branding colors we are working on. 

Best way to do this is to programmatically update the CSS variables we have in there Vs trying to create a centralized theming. Theming properly and updating all css across all components will be a humongous undertaking. So let's just try CSS variable modifications. 

Either way this is a larger task than it may appear at first sight both in terms of some thoughtful design work as well as execution.

**Comment by fire** [comment]
@dragonlvx and @coffeeorgreentea Talked about enterprised themed enhancement of Magick
