### ISSUE TITLE
Status bar at bottom + move spell saving, spell running status to it

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#381]
- [ ] Add status bar to bottom
- [ ] Show autosave on left
- [ ] Show spell running / complete on right
<img width="1512" alt="Screenshot 2023-03-11 at 4 35 32 PM" src="https://user-images.githubusercontent.com/18633264/224517819-be386f42-96a2-47ff-8b51-0d4689cff7d9.png">

**Comment by michaelsharpe** [comment]
We should also have it include a plugin option for any plugin to register data and stream data to it.
