### ISSUE TITLE
Layouts + layout templates

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#382]
Right now we just have one layout and we need to continuously move our window panes around.

We should have multiple layouts, and switch between them.

- [ ] Default layout - shows basically everything
- [ ] Prompt Engineering - show graph, inspector, text editor and playtest
- [ ] Troubleshooting - show graph, inspector, console and playtest
- [ ] Fullscreen - show graph

**Comment by michaelsharpe** [comment]
It would also be pretty trivial to allow users to create layouts for themselves as they need it. 

We should also look at the best UX for switching templates on an existing tab.
