### ISSUE TITLE
Engine imported directly into Next.js project

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#407]

**Comment by michaelsharpe** [comment]
@lalalune Can we get some clarification on this one?  Not sure what it means.

**Comment by lalalune** [comment]
The goal is to make it so we can import our editor directly into a Next.js project, the problem is that the react-router is not compatible with next-router, but if we shift our exports around and import directly into the pages it'll be fine

**Comment by coffeeorgreentea** [comment]
closed as dupe of #328
