### ISSUE TITLE
Create a test suite of Node tests to make Magick robust.

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#42]
We should really have a handful of core tests that ensure essential functionality is working. Subspells. Spell runner. Core components. 

This might be a single robust spell with subspells that runs on PR that tests almost everything. Though AI services are mocked. Interface makes this easy to do. 

We should be able to ensure that all basic functionality for now is secure once main branch is stable. We can expand to more robust and granular tests after.

**Comment by fire** [comment]
@Knar33 told me he was working on this. Let me know if this is incorrect.

**Comment by lalalune** [comment]
@Knar33 can we get this running in our CI/CD pipeline
