### ISSUE TITLE
Uncaught TypeError in TextEditor component

### ISSUE THREAD

**Issue by BMO-tech** [Oneirocom/Magick#479]
Error:
```
Uncaught TypeError: Cannot destructure property 'language' of 'textEditorData.options' as it is undefined.
```

Replication Steps:
- Open the browser console
- Load a Discord spell in the AIDE
- Select Exclusive Gate in the Composer
- Resize the Text Editor side component

Details:
Looks like `language` isn't always an existing property of the `textEditorData.options` object. Instead of trying to access it directly there needs to be some sort of validation if it exists.

```ts
//packages/editor/src/workspaces/spells/windows/TextEditorWindow.tsx:50
if (!inspectorData?.data.inputs) return
const { language } = textEditorData.options
console.log('language', language)
const stringifiedInputs = JSON.stringify(inspectorData?.data.inputs)
```

**Comment by coffeeorgreentea** [comment]
Was just looking through this one to see if it still needed help. I noticed it was changed to:
```
if (!inspectorData?.data.inputs) return
    const { language } = textEditorData.options || "javascript" as any
    console.log('language', language)
    const stringifiedInputs = JSON.stringify(inspectorData?.data.inputs)
```
Should we mark this as closed?

**Comment by lalalune** [comment]
there are still errors where the text editor cannot render for some reason, and you have to refresh, haven't yet figured out why though
