### ISSUE TITLE
Support external plugins

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#483]

**Comment by fire** [comment]
I did some design for this. Free free to edit this comment.

## What is the Context and Problem Statement this is trying to solve?

Support external plugins to make open source nature of Magick IDE usable to add new functionality.

## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams.

A few options come to mind.

2. Show a gallery from a cloud marketplace
3. Provide a zip
1. Provide a url form to like a github page

## Describe the proposed option and how it helps to overcome the problem or limitation

This will make using new functionality easier for new developers.

## Negative Consequences

1. May require web access.

## Positive Consequences

1. Democratize community enhancements
