### ISSUE TITLE
Update Docusarus to 3.0 alpha

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#484]
Right now we are using Docusaurus 2, which uses React 17. This is causing a whole bunch of security issues that are not easy to fix.

Docusaurus 3 is almost out, like in the next few weeks. If we update then all of our security issues should go away. There are no issues in the core Magick stuff, just in the docs.

**Comment by fire** [comment]
What is blocking on `Docusaurus 2`?

- [ ] turn on `Docusaurus 2` dependencies
- [ ] ???
- [ ] Validate nothing broke

**Comment by fire** [comment]
We are now on https://github.com/facebook/docusaurus/releases/tag/v2.4.0.

https://github.com/Oneirocom/Magick/blob/42e7df97d3ede2dbd8d432dfd353312738d04943/package.json#L46

The cicd isn't failing anymore. https://github.com/Oneirocom/Magick/issues/713
