### ISSUE TITLE
Cannot read properties of undefined at Output.ts

### ISSUE THREAD

**Issue by 0xPetra** [Oneirocom/Magick#495]
I just pulled the latest version from development and I'm getting this error when running the generation spell:

`TypeError: Cannot read properties of undefined (reading '0')`

Just checked and the error comes from `Oputput.ts` in this line of code:

```
  const event =
      inputs?.event?.[0] || (Object.values(module.inputs)[0] as any)[0]
```

Inputs don't have an `event` and module doesn't have `inputs`. So this triggers the error.

**Comment by lalalune** [comment]
This has been worked on with additional null checks and should be resolved, I haven't seen it so far.
