### ISSUE TITLE
import/export project

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#54]
A project for now will be considered all the spells in a person's workspace, since everything currently is local and personal.  A project will be all the spells in the DB, along with a file `spellbook.json` or similar which is at the root.  The spellbook will list the name of all the spells.  All spells, plus this spellbook.json, will be zipped and downloaded.

For import, someone selects the spellbook.json and all the spells, and uploads them.  We read the spellbook and then load all the spells in.  

note: spellbook may not be needed for this.  But there may be metadata we want to associate anyways and it may be good to set the pattern now.

**Comment by lalalune** [comment]
Now that everything is keyed by projectId, this should be as simple as creating a composite JSON of all assets associated with the current project -- spells and agents in particular for now.
- When user goes to File > Export project, it should pull all of this into a single JSON and download as <projectId>.<date>.project.json
- "File > Export Project"

- import is a "replace" operation that deletes all current project files and replaces them with the imported ones. it should be "File > Replace Project" so users are not confused
- when a user imports the project, we warn them, then delete all files with their current project and replace them
- in the cloud we have multiple project workspaces, so we will have a non-replacing import that adds a new project, we can ignore this for now
