### ISSUE TITLE
Get all packages into typedoc / docusaurus

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#560]
We have typedoc generation from Docusaurus. Right now it pulls in engine classes. We should have it pull in all classes across all plugins, packages and apps. Then we can generate fine tune dataset for all of our documentation.

The reason for this, and the reason we're prioritizing it, is because we want to import this typedoc into a script to generate a searchable document corpus and fine tune model.

**Comment by fire** [comment]
Plan is to get a list of all classes that are empty, partial or complete and complete them.

**Comment by fire** [comment]
Working on this.

**Comment by fire** [comment]
- [*] Research typedoc generation in Docusaurus
- [*] Identify classes from plugins, packages, and apps
```
grep -r -o -E 'class [A-Za-z0-9_]+( extends [A-Za-z0-9_]+)?' /path/to/your/project --exclude-dir=node_modules | awk -F: '{print $1 " -> " $2}' | awk '{print $1 " -> " $2 " " $3}'
```

I'll post a github checklist in a bit.

**Comment by fire** [comment]
grep -r -o -E 'class [A-Za-z0-9_]+( extends [A-Za-z0-9_]+)?' ./Magick --exclude-dir=node_modules | awk -F: '{print $1 " -> " $2}' | awk '{print $1 " -> " $2 " " $3}' | grep -P '(?<!\w)[A-Z][a-z]*[A-Z][A-Za-z]*(?!\w)' | grep -v -w -f <(echo -e "Buffer\nURL\nconsole\nprocess\nquerystring\nstream\nutil\nassert\nfs\npath\nos\nvm\nchild_process\ncluster\nhttp\nhttps\nnet\npunycode\nreadline\nrepl\ntls\ncrypto\ndns\nevents\nurl\nzlib") | sed 's/^.\{,2\}//' | sort

<details>
  <summary>Click to toggle visibility</summary>
    - [ ] class AddConnectionAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/connection.ts
    - [ ]     class AddNodeAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/node.ts
    - [ ]     class Agent -> Magick/packages/agents/src/lib/Agent.ts
    - [ ]     class AgentExecutor -> Magick/plugins/langchain/shared/src/nodes/AgentRecommender.ts
    - [ ]     class AgentManager -> Magick/packages/agents/src/lib/AgentManager.ts
    - [ ]     class AgentService -> Magick/packages/core/server/src/services/agents/agents.class.ts
    - [ ]     class Alert -> Magick/packages/core/shared/src/nodes/utility/AlertMessage.ts
    - [ ]     class ApiService -> Magick/plugins/rest/server/src/services/api/api.class.ts
    - [ ]     class ArrayControl -> Magick/packages/core/shared/src/dataControls/ArrayControl.ts
    - [ ]     class ArrayToJSON -> Magick/packages/core/shared/src/nodes/array/ArrayToJSON.ts
    - [ ]     class ArrayVariable -> Magick/packages/core/shared/src/nodes/array/ArrayVariable.ts
    - [ ]     class AutoArrange -> Magick/packages/editor/src/plugins/autoArrangePlugin/auto-arrange.js
    - [ ]     class AvatarPlugin -> Magick/plugins/avatar/client/src/index.ts
    - [ ]     class BabyAGI -> Magick/plugins/discord/shared/src/nodes/BabyAGI.ts
    - [ ]     class BlinkManager -> Magick/plugins/avatar/client/src/utils/blink.manager.js
    - [ ]     class BlueskyConnector -> Magick/plugins/bluesky/server/src/connectors/bluesky.ts
    - [ ]     class BooleanControl -> Magick/packages/core/shared/src/dataControls/BooleanControl.ts
    - [ ]     class BooleanGate -> Magick/packages/core/shared/src/nodes/flow/BooleanGate.ts
    - [ ]     class BooleanVariable -> Magick/packages/core/shared/src/nodes/boolean/BooleanVariable.ts
    - [ ]     class BullQueue -> Magick/packages/cloud-agent-manager/src/lib/MessageQueues/BullMQ.ts
    - [ ]     class CallContractFunctionRead -> Magick/plugins/ethereum/shared/src/nodes/CallContractFunctionRead.ts
    - [ ]     class CallContractFunctionWrite -> Magick/plugins/ethereum/shared/src/nodes/CallContractFunctionWrite.ts
    - [ ]     class CancelTask -> Magick/plugins/task/shared/src/nodes/CancelTask.ts
    - [ ]     class Cast -> Magick/packages/core/shared/src/nodes/utility/Cast.ts
    - [ ]     class CheckForRecentTxFromWallet -> Magick/plugins/ethereum/shared/src/nodes/CheckForRecentTxFromWallet.ts
    - [ ]     class ClientPlugin -> Magick/packages/core/shared/src/plugin.ts
    - [ ]     class ClientPluginManager -> Magick/packages/core/shared/src/plugin.ts
    - [ ]     class CloudAgentManager -> Magick/packages/cloud-agent-manager/src/lib/CloudAgentManager.ts
    - [ ]     class CloudAgentWorker -> Magick/packages/cloud-agent-worker/src/lib/cloud-agent-worker.ts
    - [ ]     class CloudJwtService -> Magick/packages/core/server/src/auth/cloudAuthentication.ts
    - [ ]     class CodeControl -> Magick/packages/core/shared/src/dataControls/CodeControl.ts
    - [ ]     class CombineText -> Magick/packages/core/shared/src/nodes/text/CombineText.ts
    - [ ]     class CommentManager -> Magick/packages/editor/src/plugins/commentPlugin/manager.js
    - [ ]     class CompileContract -> Magick/plugins/ethereum/shared/src/nodes/CompileContract.ts
    - [ ]     class CompleteTask -> Magick/plugins/task/shared/src/nodes/CompleteTask.ts
    - [ ]     class ComplexStringMatcher -> Magick/packages/core/shared/src/nodes/text/ComplexStringMatcher.ts
    - [ ]     class ComposeObject -> Magick/packages/core/shared/src/nodes/object/ComposeObject.ts
    - [ ]     class ComputeNatalChart -> Magick/plugins/esoterica/shared/src/nodes/ComputeNatalChart.ts
    - [ ]     class ConnectionActionHelper -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/connection.ts
    - [ ]     class CosineSimilarity -> Magick/packages/core/shared/src/nodes/embedding/CosineSimilarity.ts
    - [ ]     class CreateTask -> Magick/plugins/task/shared/src/nodes/CreateTask.ts
    - [ ]     class CreateTextEmbedding -> Magick/packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
    - [ ]     class CurrentTime -> Magick/packages/core/shared/src/nodes/utility/CurrentTime.ts
    - [ ]     class CustomMenu -> Magick/packages/editor/src/plugins/contextMenu/react-menu/index.tsx
    - [ ]     class DataControl -> Magick/packages/core/shared/src/plugins/inspectorPlugin/DataControl.ts
    - [ ]     class Delete -> Magick/packages/core/shared/src/nodes/database/Delete.ts
    - [ ]     class DeleteTask -> Magick/plugins/task/shared/src/nodes/DeleteTask.ts
    - [ ]     class DeployContract -> Magick/plugins/ethereum/shared/src/nodes/DeployContract.ts
    - [ ]     class DiscordConnector -> Magick/plugins/discord/server/src/connectors/discord.ts
    - [ ]     class DiscordJoinVoice -> Magick/plugins/discord/shared/src/nodes/DiscordJoinVoice.ts
    - [ ]     class DiscordLeaveVoice -> Magick/plugins/discord/shared/src/nodes/DiscordLeaveVoice.ts
    - [ ]     class DiscordListTextChannels -> Magick/plugins/discord/shared/src/nodes/DiscordListTextChannels.ts
    - [ ]     class DiscordListVoiceChannels -> Magick/plugins/discord/shared/src/nodes/DiscordListVoiceChannels.ts
    - [ ]     class DocumentService -> Magick/packages/core/server/src/services/documents/documents.class.ts
    - [ ]     class DocumentToContent -> Magick/packages/core/shared/src/nodes/document/DocumentToContent.ts
    - [ ]     class DragNodeAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/node.ts
    - [ ]     class DropdownControl -> Magick/packages/core/shared/src/dataControls/DropdownControl.ts
    - [ ]     class Echo -> Magick/packages/core/shared/src/nodes/utility/Echo.ts
    - [ ]     class ElectronCapacitorApp -> Magick/apps/client/electron/src/setup.ts
    - [ ]     class EmptyControl -> Magick/packages/core/shared/src/dataControls/EmptyControl.ts
    - [ ]     class Equal -> Magick/packages/core/shared/src/nodes/number/Equal.ts
    - [ ]     class ErrorNode -> Magick/packages/core/shared/src/nodes/utility/Error.ts
    - [ ]     class EthereumClient -> Magick/plugins/ethereum/server/src/connectors/ethereum.ts
    - [ ]     class EvaluateText -> Magick/packages/core/shared/src/nodes/text/EvaluateText.ts
    - [ ]     class ExclusiveGate -> Magick/packages/core/shared/src/nodes/flow/ExclusiveGate.ts
    - [ ]     class ExtractRelationship -> Magick/packages/core/shared/src/nodes/embedding/ExtractRelationship.ts
    - [ ]     class FeathersSyncReporter -> Magick/packages/cloud-agent-manager/src/lib/Reporters/FeathersSyncReporter.ts
    - [ ]     class FewshotControl -> Magick/packages/core/shared/src/dataControls/FewshotControl.ts
    - [ ]     class FindTextEmbedding -> Magick/packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts
    - [ ]     class FineTuneManager -> Magick/plugins/finetune/server/src/index.ts
    - [ ]     class FinishTaskStep -> Magick/plugins/task/shared/src/nodes/FinishTaskStep.ts
    - [ ]     class FrameComment -> Magick/packages/editor/src/plugins/commentPlugin/frame-comment.js
    - [ ]     class GenerateText -> Magick/packages/core/shared/src/nodes/text/GenerateText.ts
    - [ ]     class GetDocuments -> Magick/packages/core/shared/src/nodes/document/GetDocuments.ts
    - [ ]     class GetERC20BalanceFromWallet -> Magick/plugins/ethereum/shared/src/nodes/GetERC20BalanceFromWallet.ts
    - [ ]     class GetNativeBalanceFromWallet -> Magick/plugins/ethereum/shared/src/nodes/GetNativeBalanceFromWallet.ts
    - [ ]     class GetRecentTxsFromWallet -> Magick/plugins/ethereum/shared/src/nodes/GetRecentTxsFromWallet.ts
    - [ ]     class GetRecentTxsFromWallet -> Magick/plugins/ethereum/shared/src/nodes/GetRecentTxsFromWallet.ts
    - [ ]     class GetValueFromArray -> Magick/packages/core/shared/src/nodes/array/GetValueFromArray.ts
    - [ ]     class GetValuesFromObject -> Magick/packages/core/shared/src/nodes/object/GetValuesFromObject.ts
    - [ ]     class GlobalsManager -> Magick/packages/core/shared/src/globals.ts
    - [ ]     class GmailConnector -> Magick/plugins/gmail/server/src/connectors/gmail.ts
    - [ ]     class GoogleSearchService -> Magick/plugins/search/server/src/services/google-search/google-search.class.ts
    - [ ]     class GreaterThan -> Magick/packages/core/shared/src/nodes/number/GreaterThan.ts
    - [ ]     class GreaterThanOrEqual -> Magick/packages/core/shared/src/nodes/number/GreaterThanOrEqual.ts
    - [ ]     class InRange -> Magick/packages/core/shared/src/nodes/number/InRange.ts
    - [ ]     class InfoControl -> Magick/packages/core/shared/src/plugins/inspectorPlugin/dataControls/InfoControl.tsx
    - [ ]     class InlineComment -> Magick/packages/editor/src/plugins/commentPlugin/inline-comment.js
    - [ ]     class InputComponent -> Magick/packages/core/shared/src/nodes/io/Input.ts
    - [ ]     class InputControl -> Magick/packages/core/shared/src/dataControls/InputControl.ts
    - [ ]     class InputGeneratorControl -> Magick/packages/core/shared/src/dataControls/InputGenerator.ts
    - [ ]     class Insert -> Magick/packages/core/shared/src/nodes/database/Insert.ts
    - [ ]     class IsNullOrUndefined -> Magick/packages/core/shared/src/nodes/flow/IsNullOrUndefined.ts
    - [ ]     class IsVariableTrue -> Magick/packages/core/shared/src/nodes/boolean/IsVariableTrue.ts
    - [ ]     class Javascript -> Magick/packages/core/shared/src/nodes/code/Javascript.ts
    - [ ]     class JoinListComponent -> Magick/packages/core/shared/src/nodes/array/JoinList.ts
    - [ ]     class JupyterNotebook -> Magick/packages/core/shared/src/nodes/experimental/JupyterNotebook.ts
    - [ ]     class LessThan -> Magick/packages/core/shared/src/nodes/number/LessThan.ts
    - [ ]     class LessThanOrEqual -> Magick/packages/core/shared/src/nodes/number/LessThanOrEqual.ts
    - [ ]     class LipSync -> Magick/plugins/avatar/client/src/utils/lip.sync.js
    - [ ]     class Log -> Magick/packages/core/shared/src/nodes/utility/Log.ts
    - [ ]     class LogicalOperator -> Magick/packages/core/shared/src/nodes/boolean/LogicalOperator.ts
    - [ ]     class LoopManager -> Magick/plugins/loop/server/src/index.ts
    - [ ]     class LoopPlugin -> Magick/plugins/loop/client/src/index.ts
    - [ ]     class MagickComponent -> Magick/packages/core/shared/src/engine.ts
    - [ ]     class MagickConsole -> Magick/packages/core/shared/src/plugins/consolePlugin/MagickConsole.ts
    - [ ]     class MagickEditor -> Magick/packages/core/shared/src/types.ts
    - [ ]     class MagickEngineComponent -> Magick/packages/core/shared/src/engine.ts
    - [ ]     class MagickInterfaceProvider -> Magick/packages/editor/src/contexts/MagickInterfaceProvider.tsx
    - [ ]     class MainMenu -> Magick/packages/editor/src/plugins/contextMenu/main-menu.ts
    - [ ]     class Merge -> Magick/packages/core/shared/src/nodes/object/MergeObjects.ts
    - [ ]     class ModelControl -> Magick/packages/core/shared/src/dataControls/ModelControl.ts
    - [ ]     class ModuleManager -> Magick/packages/core/shared/src/plugins/modulePlugin/module-manager.ts
    - [ ]     class MovieTitleToID -> Magick/plugins/esoterica/shared/src/nodes/MovieTitleToID.ts
    - [ ]     class MovieTrivia -> Magick/plugins/esoterica/shared/src/nodes/MovieTrivia.ts
    - [ ]     class MultiSocketGeneratorControl -> Magick/packages/core/shared/src/dataControls/MultiSocketGenerator.ts
    - [ ]     class MyNode -> Magick/packages/editor/src/components/Node/Node.tsx
    - [ ]     class NodeAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/node.ts
    - [ ]     class NodeMenu -> Magick/packages/editor/src/plugins/contextMenu/node-menu.ts
    - [ ]     class NumberControl -> Magick/packages/core/shared/src/dataControls/NumberControl.ts
    - [ ]     class NumberVariable -> Magick/packages/core/shared/src/nodes/number/NumberVariable.ts
    - [ ]     class ObjectToJSON -> Magick/packages/core/shared/src/nodes/object/ObjectToJSON.ts
    - [ ]     class OrGate -> Magick/packages/core/shared/src/nodes/flow/OrGate.ts
    - [ ]     class Output -> Magick/packages/core/shared/src/nodes/io/Output.ts
    - [ ]     class OutputGeneratorControl -> Magick/packages/core/shared/src/dataControls/OutputGenerator.ts
    - [ ]     class ParseJSON -> Magick/packages/core/shared/src/nodes/object/JSONToObject.ts
    - [ ]     class PgNotifyReporter -> Magick/packages/cloud-agent-manager/src/lib/Reporters/PgNotifyReporter.ts
    - [ ]     class PlaytestControl -> Magick/packages/core/shared/src/dataControls/PlaytestControl.ts
    - [ ]     class PluginEmbeddings -> Magick/packages/core/server/src/customEmbeddings.ts
    - [ ]     class PluginManager -> Magick/packages/core/shared/src/plugin.ts
    - [ ]     class PostgresVectorStoreCustom -> Magick/packages/core/server/src/vectordb.ts
    - [ ]     class ProfanityFilter -> Magick/packages/core/shared/src/nodes/text/ProfanityFilter.ts
    - [ ]     class ProjectsService -> Magick/packages/core/server/src/services/projects/projects.class.ts
    - [ ]     class Python -> Magick/packages/core/shared/src/nodes/code/Python.ts
    - [ ]     class QAService -> Magick/plugins/qa/server/src/services/QA/qa.class.ts
    - [ ]     class QueryPinecone -> Magick/plugins/pinecone/shared/src/nodes/QueryPinecone.ts
    - [ ]     class RandomGate -> Magick/packages/core/shared/src/nodes/flow/RandomGate.ts
    - [ ]     class RedisPubSub -> Magick/packages/redis-pubsub/src/lib/redis-pubsub.ts
    - [ ]     class RemapArray -> Magick/packages/core/shared/src/nodes/array/RemapArray.ts
    - [ ]     class RemoveConnectionAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/connection.ts
    - [ ]     class RemoveNodeAction -> Magick/packages/core/shared/src/plugins/historyPlugin/actions/node.ts
    - [ ]     class ReplaceText -> Magick/packages/core/shared/src/nodes/text/ReplaceText.ts
    - [ ]     class Request -> Magick/packages/core/shared/src/nodes/io/Request.ts
    - [ ]     class RequestService -> Magick/packages/core/server/src/services/requests/requests.class.ts
    - [ ]     class Respond -> Magick/packages/core/shared/src/nodes/io/Respond.ts
    - [ ]     class RestPlugin -> Magick/plugins/rest/server/src/index.ts
    - [ ]     class RunButtonControl -> Magick/packages/core/shared/src/plugins/cachePlugin/RunLastArguments.tsx
    - [ ]     class RunSpell -> Magick/packages/core/shared/src/nodes/magick/runSpell.ts
    - [ ]     class RunSpell -> Magick/packages/core/shared/src/spellManager/runSpell.ts
    - [ ]     class SearchGoogle -> Magick/plugins/search/shared/src/nodes/SearchGoogle.ts
    - [ ]     class Select -> Magick/packages/core/shared/src/nodes/database/Select.ts
    - [ ]     class ServerPlugin -> Magick/packages/core/shared/src/plugin.ts
    - [ ]     class ServerPluginManager -> Magick/packages/core/shared/src/plugin.ts
    - [ ]     class Skill -> Magick/packages/core/shared/src/nodes/io/Skill.ts
    - [ ]     class SnapGrid -> Magick/packages/editor/src/plugins/areaPlugin/snap.ts
    - [ ]     class SocketGeneratorControl -> Magick/packages/core/shared/src/dataControls/SocketGenerator.ts
    - [ ]     class SocketGeneratorControl -> Magick/packages/core/shared/src/dataControls/SocketGenerator.ts
    - [ ]     class SolidityService -> Magick/plugins/ethereum/server/src/services/solidity/solidity.class.ts
    - [ ]     class SpeechUtils -> Magick/packages/editor/src/utils/speechUtils.ts
    - [ ]     class SpellByName -> Magick/packages/core/shared/src/nodes/io/SpellByName.ts
    - [ ]     class SpellComponent -> Magick/packages/core/shared/src/nodes/io/Spell.ts
    - [ ]     class SpellControl -> Magick/packages/core/shared/src/dataControls/SpellControl.ts
    - [ ]     class SpellError -> Magick/packages/core/shared/src/utils/SpellError.ts
    - [ ]     class SpellManager -> Magick/packages/core/shared/src/spellManager/SpellManager.ts
    - [ ]     class SpellRunner -> Magick/packages/core/shared/src/spellManager/SpellRunner.ts
    - [ ]     class SpellRunnerService -> Magick/packages/core/server/src/services/spell-runner/spell-runner.class.ts
    - [ ]     class SpellService -> Magick/packages/core/server/src/services/spells/spells.class.ts
    - [ ]     class StoreDocument -> Magick/packages/core/shared/src/nodes/document/StoreDocument.ts
    - [ ]     class StringVariable -> Magick/packages/core/shared/src/nodes/text/StringVariable.ts
    - [ ]     class SwitchControl -> Magick/packages/core/shared/src/dataControls/SwitchControl.ts
    - [ ]     class SwitchGate -> Magick/packages/core/shared/src/nodes/flow/SwitchGate.ts
    - [ ]     class TaskManager -> Magick/plugins/task/server/src/index.ts
    - [ ]     class TaskPlugin -> Magick/plugins/task/client/src/index.ts
    - [ ]     class TaskService -> Magick/packages/core/server/src/services/tasks/tasks.class.ts
    - [ ]     class TextInputControl -> Magick/packages/core/shared/src/dataControls/TextInputControl.tsx
    - [ ]     class TextTemplate -> Magick/packages/core/shared/src/nodes/text/TextTemplate.ts
    - [ ]     class TextToSpeech -> Magick/packages/core/shared/src/nodes/experimental/textToSpeech.ts
    - [ ]     class TextVariable -> Magick/packages/core/shared/src/nodes/text/TextVariable.ts
    - [ ]     class TwitterConnector -> Magick/plugins/twitter/server/src/connectors/twitter.ts
    - [ ]     class Update -> Magick/packages/core/shared/src/nodes/database/Update.ts
    - [ ]     class UploadService -> Magick/packages/core/server/src/services/Upload.class.ts
    - [ ]     class Upsert -> Magick/packages/core/shared/src/nodes/database/Upsert.ts
    - [ ]     class VoiceMessage -> Magick/plugins/discord/server/src/connectors/voiceUtils/VoiceMessage.ts
    - [ ]     class WaitForAll -> Magick/packages/core/shared/src/nodes/flow/WaitForAll.ts
    - [ ]     class Worker -> Magick/plugins/gmail/server/src/connectors/IMAP.ts
    - [ ]     class Worker -> Magick/plugins/gmail/server/src/connectors/SMTP.ts
    - [ ]     class and -> Magick/packages/core/shared/src/dataControls/FewshotControl.ts
    - [ ]     class as -> Magick/packages/core/client/src/components/LoadingScreen/magick-loading.svg
    - [ ]     class constructor -> Magick/packages/core/shared/src/nodes/object/ObjectToJSON.ts
    - [ ]     class extends -> Magick/packages/core/shared/src/nodes/embedding/FindTextEmbedding.ts
    - [ ]     class extends -> Magick/packages/core/shared/src/nodes/flow/SwitchGate.ts
    - [ ]     class extends -> Magick/packages/core/shared/src/nodes/utility/AlertMessage.ts
    - [ ]     class for -> Magick/packages/core/client/src/components/TabLayout/index.tsx
    - [ ]     class for -> Magick/packages/core/shared/src/dataControls/NumberControl.ts
    - [ ]     class for -> Magick/packages/core/shared/src/nodes/array/RemapArray.ts
    - [ ]     class for -> Magick/packages/core/shared/src/nodes/document/StoreDocument.ts
    - [ ]     class for -> Magick/packages/core/shared/src/nodes/experimental/JupyterNotebook.ts
    - [ ]     class for -> Magick/packages/core/shared/src/plugins/inspectorPlugin/DataControl.ts
    - [ ]     class from -> Magick/packages/core/shared/src/dataControls/BooleanControl.ts
    - [ ]     class from -> Magick/packages/editor/src/DataControls/index.tsx
    - [ ]     class from -> Magick/plugins/ethereum/shared/src/nodes/GetRecentTxsFromWallet.ts
    - [ ]     class inherits -> Magick/packages/core/shared/src/nodes/object/MergeObjects.ts
    - [ ]     class is -> Magick/packages/core/shared/src/dataControls/OutputGenerator.ts
    - [ ]     class is -> Magick/packages/core/shared/src/nodes/boolean/LogicalOperator.ts
    - [ ]     class is -> Magick/packages/core/shared/src/plugins/inspectorPlugin/dataControls/InfoControl.tsx
    - [ ]     class is -> Magick/packages/core/shared/src/plugins/inspectorPlugin/dataControls/InfoControl.tsx
    - [ ]     class is -> Magick/plugins/ethereum/shared/src/nodes/CompileContract.ts
    - [ ]     class method -> Magick/packages/core/shared/src/nodes/text/TextVariable.ts
    - [ ]     class name -> Magick/LICENSE
    - [ ]     class of -> Magick/packages/core/shared/src/dataControls/CodeControl.ts
    - [ ]     class of -> Magick/packages/core/shared/src/dataControls/PlaytestControl.ts
    - [ ]     class of -> Magick/packages/core/shared/src/plugins/inspectorPlugin/dataControls/InfoControl.tsx
    - [ ]     class representing -> Magick/plugins/ethereum/shared/src/nodes/GetNativeBalanceFromWallet.ts
    - [ ]     class represents -> Magick/packages/core/shared/src/dataControls/BooleanControl.ts
    - [ ]     class represents -> Magick/packages/core/shared/src/dataControls/SocketGenerator.ts
    - [ ]     class represents -> Magick/packages/core/shared/src/nodes/text/ReplaceText.ts
    - [ ]     class represents -> Magick/packages/core/shared/src/nodes/text/StringVariable.ts
    - [ ]     class string -> Magick/plugins/finetune/client/src/components/MetadataCard.tsx
    - [ ]     class that -> Magick/packages/core/shared/src/dataControls/FewshotControl.ts
    - [ ]     class that -> Magick/packages/core/shared/src/dataControls/InputControl.ts
    - [ ]     class that -> Magick/packages/core/shared/src/dataControls/SpellControl.ts
    - [ ]     class that -> Magick/packages/core/shared/src/nodes/embedding/CreateTextEmbedding.ts
    - [ ]     class that -> Magick/packages/core/shared/src/nodes/embedding/ExtractRelationship.ts
    - [ ]     class that -> Magick/packages/core/shared/src/nodes/text/EvaluateText.ts
    - [ ]     class that -> Magick/packages/editor/src/plugins/contextMenu/node-menu.ts
    - [ ]     class that -> Magick/plugins/esoterica/shared/src/nodes/MovieTrivia.ts
    - [ ]     class that -> Magick/plugins/task/shared/src/nodes/CreateTask.ts
    - [ ]     class that -> Magick/plugins/task/shared/src/nodes/FinishTaskStep.ts
    - [ ]     class used -> Magick/packages/core/shared/src/utils/SpellError.ts
    - [ ]     class which -> Magick/plugins/pinecone/shared/src/nodes/QueryPinecone.ts

</details>
