### ISSUE TITLE
[BUG] store event node is not authenticated

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#596]
may need to switch to using an internal feathers service rather than an API call.  I imagine it is using a getSpell which makes an unauthenticated fetch request.

<img width="689" alt="Screenshot 2023-04-05 at 4 31 36 PM" src="https://user-images.githubusercontent.com/2397603/230235381-0a86132a-c342-49a6-aeb1-e290aee76261.png">

**Comment by lalalune** [comment]
Fixed in latest push
