### ISSUE TITLE
[UX] user zoom control setting

### ISSUE THREAD

**Issue by michaelsharpe** [Oneirocom/Magick#630]
user setting option to control zoom sensitivity.

**Comment by dragonlvx** [comment]
@FabriceIRANKUNDA @coffeeorgreentea 
we need to fix the zoom feature on the IDE so it's not hyper sensitive when zooming on a track pad or magic mouse.

Let me know when you've updated this and I will review to make sure it feels good.

**Comment by rjphnx** [comment]
A number of users and team members are blocked from navigating the IDE because of this zoom bug. It is unusable in its current form.

**Comment by coffeeorgreentea** [comment]
> A number of users and team members are blocked from navigating the IDE because of this zoom bug. It is unusable in its current form.

i spent a bit last week looking into this with not much luck but am going to try a different approach this week. Rete does not have a clear way to do this

**Comment by coffeeorgreentea** [comment]
its also hard for me to test, because it works fine on my trackpad.
@rjphnx @dragonlvx can you tell me what hardware your using?

**Comment by coffeeorgreentea** [comment]
@rjphnx @dragonlvx go to this link: https://rete.js.org/#/examples/basic
does the zooming work fine on this page? if so lmk

**Comment by rjphnx** [comment]
@coffeeorgreentea Macbook Pro -trackpad and Magic Mouse.

"...on this page?"

Yes, it does.

**Comment by FabriceIRANKUNDA** [comment]
@rjphnx @dragonlvx I don't know how to reproduce the issue you're mentioning,
I'm on Macbook Pro and it seems to work smoothly on my end. Please add a video to clarify better what the issue looks like.

**Comment by dragonlvx** [comment]
@FabriceIRANKUNDA 

The following screen capture shows me trying to zoom in with Figma and then trying to do the same thing in the Magick IDE environment. As you can see, it's a lot more difficult to zoom in with the exact accuracy and smoothness that I get in programs like Figma, Illustrator or Photoshop.
This is video was with a magic mouse (apple) on my macbook, in google chrome.

Let me know if this makes sense or you want me to explain in more detail. 

https://github.com/Oneirocom/Magick/assets/125402897/d25a7a4d-5af2-4db7-8019-8df498b17a07

**Comment by FabriceIRANKUNDA** [comment]
@dragonlvx, this issue has been improved. Please take some time to test it out whenever you can.
