### ISSUE TITLE
When right clicking within IDE, allow typing to automatically fill in 'search' field

### ISSUE THREAD

**Issue by rjphnx** [Oneirocom/Magick#635]
![ScreenCap 2023-04-12 at 17 26 17](https://user-images.githubusercontent.com/12023783/231588960-26a2c443-6a7b-428a-88c9-0cca396d75dd.jpg)

See screenshot for example

**Comment by lalalune** [comment]
good catch

**Comment by coffeeorgreentea** [comment]
i stumbled across this while doing something else and fixed it here:
https://github.com/Oneirocom/Magick/commit/2dfdbb52b933d70d172d7f1eb6ccc6b2cb4b3fa1

**Comment by FabriceIRANKUNDA** [comment]
Awesome!

> i stumbled across this while doing something else and fixed it here: [2dfdbb5](https://github.com/Oneirocom/Magick/commit/2dfdbb52b933d70d172d7f1eb6ccc6b2cb4b3fa1)
