### ISSUE TITLE
Update code completion with model provider choices

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#650]
Right now we can complete and generate code nodes, but it's reliant on OpenAI. Would be great to make this a setting and let users select their model provider. Once we integrate PaLM etc this will become more important.

**Comment by coffeeorgreentea** [comment]
can add Codegen and Alpaca for this via banana-plugin
https://github.com/lucataco/serverless-template-codegen-2B-multi/tree/197973c6709816b50e647dc2a97bc63d9054078b
https://app.banana.dev/templates/sahil280114/code-alpaca/1
https://app.banana.dev/templates/sahil280114/code-alpaca-13b/1

**Comment by lalalune** [comment]
Awesome. Immediate need to enable this:
1. Add code completion providers (similar to text, chat, embeddings)
2. Add Provider validation (has API key) and dropdown to completion in Text Editor window
3. Hook in the completion handler to be called here
4. Give status update, success, running, failure
