### ISSUE TITLE
The docs mention binary releases at an empty link

### ISSUE THREAD

**Issue by fire** [Oneirocom/Magick#729]
### Magick version

https://github.com/Oneirocom/Magick/commit/a6c8eb1b98c675ddc601addafc41b78e41cbfaeb

### System information

Windows, 10

### Issue description

The docs mention binary releases at an empty link.

### Steps to reproduce

1. Read https://academy.magickml.com/docs/Getting%20Started
1. Open 
https://github.com/Oneirocom/Magick/releases
2. Check that it is empty.

**Comment by lalalune** [comment]
If you're interested in taking this on, we have Capacitor set up to build native binaries, we just need the CI/CD in github with actions deployed. It's gonna take some banging your head against it, but it means getting a native downloadable client we can put on all the devices :)

**Comment by fire** [comment]
Part of https://github.com/Oneirocom/Magick/pull/767

**Comment by fire** [comment]
Focus on the documentation work.

**Comment by fire** [comment]
Use task #405 to track this.
