### ISSUE TITLE
Starter discord bot sends all messages as if they were all from "user" or all from "assistant" instead of alternating

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#743]
### Magick version

ccee4d4

### System information

Ubuntu 22.04.1, firefox

### Issue description

The starter spell Discord bot is sending all messages to ChatGPT as the same "role", instead of using the role that is stored in the event. In my events window the roles are correctly being stored, and when I view the input of the text generation node I can see they are being properly passed in, but I think the text generation node is not taking into account the sender and applying that as the "role" property in the message. See screenshot below of a sample request for a conversation being sent to chatgpt which has all role properties set as "assistant". I have also had it where all messages are sent as "user".

![image](https://user-images.githubusercontent.com/4692561/235239618-2d9ec87d-fdf1-4b33-bfd9-0488de98889e.png)

### Steps to reproduce

- Create a starter discord bot
- send a few messages back and forth to the bot
- Check the outgoing requests for the role properties of the messages

**Comment by fire** [comment]
Is https://github.com/Oneirocom/Magick/issues/735 the same bug? Can we combine them?

**Comment by Knar33** [comment]
> Is #735 the same bug? Can we combine them?

I don't think so, this seems like a bug in the way the text generation node formats events into messages to be sent to OpenAI. Solving this might not solve #735, which is probably more related to how messages are being sent and the order they're being sent in.
