### ISSUE TITLE
[ELIZA] Profanity Filter, Moderation API and Abuse classifier

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#764]
We want to make sure that people don't abuse our agent. We also want to make sure our agent doesn't abuse them

- [x] Add profanity filter onto the front of all user requests, right off the bat
- [ ] Add "abuse" type to the classifier prompt
- [ ] Run moderation API call in parallel to classifier call
- [ ] WaitForAll and evaluate if the switch type is "abuse" or the moderation API is triggered

**Comment by fire** [comment]
See also: Profanity filter is too strict #779
