### ISSUE TITLE
Change the order of spells in the "Open Spell" menu to be in alphabetical order

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#775]
**Is your feature request related to a problem? Please describe.**
It is hard to find the spells I'm looking for sometimes, especially when I have a lot of spells in my project.

**Describe the solution you'd like**
It would be nice to have the spells listed in alphabetical order instead of the order they were created in.

**Comment by michaelsharpe** [comment]
We have an in-progress feature to introduce a file drawer for spells and other assets in the environment.  our current means of opening spells is an older UX approach which was when a spell was an isolated thing rather than part of a project.
