### ISSUE TITLE
Magick install on the mac requires a `npm install nx`

### ISSUE THREAD

**Issue by fire** [Oneirocom/Magick#785]
### Magick version

19b0cff98129b8da8f92115f1138029cb0e99ddb (benbot/benbot/change-inspector-ports)

### System information

Mac 13.3.1, Firefox

### Issue description

The default setup can't find nx.

### Steps to reproduce

Running `npm install` and `npm run dev`fails with:

 >  NX   Cannot find module '@nrwl/nx-darwin-x64'
 
Need to manually `npm install nx`

### Minimal reproduction project

Checkout the repository and run on a mac.

**Comment by lalalune** [comment]
That is very interesting and strange. For the most part we use nx through npx, is there any place perhaps we are calling nx directly?

**Comment by fire** [comment]
I don't think this is a problem anymore.
