### ISSUE TITLE
[BUG] Code Node Sometimes Breaks and Disappears When Text Editor Open

### ISSUE THREAD

**Issue by lalalune** [Oneirocom/Magick#795]
### Magick version

Development

### System information

Mac OSx

### Issue description

Sometimes when I'm developing, and for reasons I haven't tracked down, the Code node will break and disappear.

Seems like when I'm switching between windows which both have a code node, possibly currently selected in both? The connection is definitely between the text editor and editing code nodes in different windows.

This is *really* frustrating since it takes my code with it :)

This is probably related to the dynamic sockets.

Generally the code node feels a little buggy. Saving should save the whole graph, updating inputs can sometimes not work ideally, etc.

We should thoroughly test and make sure the nodes are reliable, work between window switches, multiple saves, closing and opening graphs, etc etc

### Steps to reproduce

Hard to reproduce. Code nodes just randomly disappear from graph. Will try to update with more information as I find it.

**Comment by Knar33** [comment]
This is happening with other nodes as well. I am frequently refreshing a spell after saving and finding nodes missing. #773 is the only one I could reproduce so far.
