### ISSUE TITLE
Duplicate spells

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#901]
### Magick version

aef2d50

### System information

Ubuntu 22.04.1, firefox

### Issue description

I somehow ended up with a couple duplicate spells. They show up in my spellbook list twice, but when I select one it selects both. They both get exported when I export my project, they do have different spell IDs but they have the same created date. I have no clue how this happened, a while back when we switched over to postgres I exported all my spells in sqlite and imported them to postgres but I only did that once. As far as I know I never tried to import these spells again, and even if I did it should have created the same spell name appended with (1). 

This happened to another spell also so it's not just a one-off thing.

![image](https://github.com/Oneirocom/Magick/assets/4692561/5503ed22-7d82-46d1-bfcd-d08ec4d214da)

![image](https://github.com/Oneirocom/Magick/assets/4692561/b642b153-604f-4fe5-86ae-d95f1303323c)

![image](https://github.com/Oneirocom/Magick/assets/4692561/6075704e-4cf4-4472-89b6-60a71ebeac2e)

### Steps to reproduce

No clue..

**Comment by lalalune** [comment]
This selection issue is fixed here: https://github.com/Oneirocom/Magick/pull/949
