### ISSUE TITLE
Add Docker requirements to Readme.md and documentation page for installation

### ISSUE THREAD

**Issue by Knar33** [Oneirocom/Magick#905]
When we switched over to Postgres we added a new requirement for running Magick, Docker. We need to update the Readme installation instructions as well as the Documentation page installation instructions to reflect the fact that users will need to install either Docker or Docker Desktop in order for Magick to run locally.

**Comment by fire** [comment]
See also https://github.com/Oneirocom/Magick/issues/849

**Comment by lalalune** [comment]
```
Local development is straightforward. You will need git, node.js 18+ installed, and Docker installed and running.

The easiest way to get up and running with Docker is to use Docker Desktop, found [here](https://www.docker.com/products/docker-desktop/). Simply run through the installation instructions and ensure it is running.
```

Seems like it's covered in the installation guide now, closing
