### ISSUE TITLE
Update omi-personality-transform-script for VRM1 so that users can drop in a VRM avatar during the creation of an agent

### ISSUE THREAD

**Issue by fire** [Oneirocom/Magick#977]
## Is your feature request related to a problem? Please describe.

VRM implementation - Users can drop in a VRM avatar during the creation of an agent so that they customize their agent virtual being.

## Describe the solution you'd like

https://github.com/xpportal/omi-personality-transform-script currently supports VRM0 and VRM1 needs to be implemented.

Work: For each gltf extension add code to copy into gltf transform following the vrm0 template.

**Describe alternatives you've considered**

* Not implementing VRM1
* Not implementing VRM at all.

**Comment by ultrabot2022** [comment]
I added screenshots of problems of loading VRM1 files with this extension in the issue list.
