### ISSUE TITLE
Full vrm0 and vrm1 support

### ISSUE THREAD

**Issue by coffeeorgreentea** [Oneirocom/Magick#984]

**Comment by fire** [comment]
![image](https://github.com/Oneirocom/Magick/assets/32321/5a2bf062-2e7b-461d-b615-733951392fe1)

https://www.creators3d.com/online-viewer

@ultrabot2022 can you post the vrm?

**Comment by ultrabot2022** [comment]
[models.zip](https://github.com/Oneirocom/Magick/files/11671227/models.zip)

Below the command to make the bbb_output.vrm file
node .\personalityOptimize.js .\bbb.vrm "tubby" "#agent is cheery" "nya nya!"

**Comment by ultrabot2022** [comment]
https://filext.com/file-extension/VRM
I checked bbb_output.vrm file on the above url. I can see this file is glb file, not vrm one.
![image](https://github.com/Oneirocom/Magick/assets/80860637/a30f55ec-05a6-4511-ae71-7f5570e6b70c)

Here is vrm file structure of bbb.vrm file
![image](https://github.com/Oneirocom/Magick/assets/80860637/8a617159-c07a-49c8-b0aa-7be05daa4306)

**Comment by fire** [comment]
@ultrabot2022 Is this complete?

**Comment by ultrabot2022** [comment]
not yet. I need to see the godot code or something else for reference

**Comment by ultrabot2022** [comment]
yes. it is completed.
